name: itable_ex
description:
version: 0.1.5
publish_to: none

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  meta: any    
  pshondation:
    git:
      url: https://github.com/pshonkaaa/package.pshondation.dart.git

  ientity:
    git:
      url: https://github.com/pshonkaaa/package.ientity.dart.git
    
  logger: any
  sqflite: any
  sqflite_common_ffi: any
  sqflite_common_ffi_web: any

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
